SSS_PFP SETTINGS:
//Lines starting with "//" are comments.
//
//Find your Steam64ID (Dec) here:
//https://www.steamidfinder.com/
//Replace "2319051092741978" and "YOURSTEAM64IDHERE" in this file
//
//Ensure you are logged into steam on your browser
//
//Find your SessionID and Cookie by going to:
//https://steamcommunity.com/actions/FileUploader?type=player_avatar_image&sId=YOURSTEAM64IDHERE
//Press F12 or right click -> Inspect
//Go to the "Application" tab
//Double click the second column for "steamLoginSecure" and copy the value
//Replace "1298541294KJSFASFASF%D5%DSKA110455601DDAAD114" in this file with the value you just copied
//Double click the second column for "sessionid" and copy the value
//Replace "sdbjh1871bhdw81db81" in this file with the value you just copied
//
//If you have any issues please first check the .log, then ensure the values in this file are correct, then open an issue on github.
//
//Profile pictures must be .jpg, .jpeg, or .png and under 1mb

Steam64ID=2319051092741978
SessionID=sdbjh1871bhdw81db81
Cookie=1298541294KJSFASFASF%D5%DSKA110455601DDAAD114