SSS_PFP SETTINGS:
//Lines starting with "//" are comments.
//
//Find your Steam64ID (Dec) here:
//https://www.steamidfinder.com/
//Replace "2319051092741978" in this file
//
//If you don't care what order the profile pictures are displayed in set Randomized to "True"
//If you are using this to "animate" your profile picture, leave Randomized as "False"
//
//If you have any issues please first check the .log, then ensure the values in this file are correct, then open an issue on github.
//
//Profile pictures must be .jpg, .jpeg, or .png and under 1mb

Steam64ID=2319051092741978
Randomized=False
